### ISSUE TITLE
Change editor position, divide discussion list.

### ISSUE THREAD

**Issue by lattekun** [dokufreaks/plugin-discussion#220] opened 2016-10-27 10:14 UTC
1. How can I change editor box to up?
   Editor box is located in bottom of discussion list.
   But it is very hard to write discussion when discussion list is too long.
2. If users write discussion 50s or 100s discussions, discussion list looks like too long.
   I think, discussion plugin need a function to divide discussion list.

How can I modify php or html source?
Please help me.

**Comment by Klap-in** [comment] 2016-10-27 13:45
The `comments()` function in the action plugin component calls the `_show()` function. This function build the thread of comments.

See https://github.com/dokufreaks/plugin-discussion/blob/master/action.php#L326

**Comment by lattekun** [comment] 2016-10-27 18:22
@Klap-in
I'm sorry, but can I tell you in detail how to modify the feature?

**Comment by Klap-in** [comment] 2016-10-28 09:03
Sorry, I have no time for doing a rewrite/improvement of this plugin.

about 1. : 
I'm wondering, do you not just request a feature that is already there? Do I remember it correctly that each comment has an own button 'Reply', which let you reply inline. (there is also a setting for threaded view, maybe that influence your view as well)

about 2 :
Is a real comment platform not better suited for your situation? This Discussion plugin is a relative simple solution. See for example: https://www.dokuwiki.org/plugin:disqus

**Comment by Klap-in** [comment] 2022-09-25 15:29
about point 1: if do you actually ask to show the most recent comments on top? This can be set with the `newestfirst` configuration setting. I consider this point as solved.

about point 2: request for pagination is a duplicate of #46. Let continue the discussion there.

**Closed by Klap-in** 2022-09-25 15:29 UTC
